version: '2.4'
services:
  web:
    image: swarnat/xbrowsersync-api:latest
    restart: always
    environment:
      XBSAPI_SERVICE_LOCATION: 'DE'
      XBSAPI_DB_TYPE: 'mysql'
      XBSAPI_DB_HOST: '10.200.1.102'
      XBSAPI_DB_NAME: 'xbrowsersync'
      XBSAPI_DB_USERNAME: 'abc'
      XBSAPI_DB_PASSWORD: 'abc'
      XBSAPI_STATUS_MESSAGE: 'Welcome to xBrowserSync'
    ports:
      - '8000:8000'
